post_install() {
    echo "-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --"
    echo "-- It is required to set the $TERMINAL environment variable to your terminal emulator."
    echo "-- Edit config.h in dwm's PKGBUILD directory (generally /var/abs/community/dwm/)"
    echo "-- and rebuild package if you want to change some settings."
    echo "-- Or, place custom config.h in \$SRCDEST/dwm/config.h and rebuild."
    echo "-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --"
}
